In [1]:
import pandas as pd

In [2]:
datas = ['读取文件，统计数字列与非数字列的比例。文件路径如下：test.xlsx']*100
df = pd.DataFrame(datas, columns=['question'])
df.head()

                              question
0  读取文件，统计数字列与非数字列的比例。文件路径如下：test.xlsx
1  读取文件，统计数字列与非数字列的比例。文件路径如下：test.xlsx
2  读取文件，统计数字列与非数字列的比例。文件路径如下：test.xlsx
3  读取文件，统计数字列与非数字列的比例。文件路径如下：test.xlsx
4  读取文件，统计数字列与非数字列的比例。文件路径如下：test.xlsx

In [3]:
train_df = pd.DataFrame(columns=['data_source', 'prompt', 'ability', 'reward_model', 'extra_info', 'raw_prompt', 'agent_name'])

In [4]:
data_source = []
prompt = []
ability = []
reward_model = []
extra_info = []
raw_prompt = []
agent_name = []

In [5]:
for idx, ques in enumerate(df['question']):
    data_source.append('code')
    p = [{"role": "user", "content": ques}]
    prompt.append(p)
    raw_prompt.append(p)
    ability.append('text')
    reward_model.append({
                "style": "rule",
                "ground_truth": "",
            })
    
    extra_info.append({
                'split': 'train',
                'index': idx,
            })
    agent_name.append('tool_agent')

In [6]:
train_df['data_source'] = data_source
train_df['prompt'] = prompt
train_df['ability'] = ability
train_df['reward_model'] = reward_model
train_df['extra_info'] = extra_info
train_df['raw_prompt'] = raw_prompt
train_df['agent_name'] = agent_name

In [7]:
train_df.head()

,data_source,prompt,ability,reward_model,extra_info,raw_prompt,agent_name
0,code,"[{'role': 'user', 'content': '读取文件，统计数字列与非数字列的...",text,"{'style': 'rule', 'ground_truth': ''}","{'split': 'train', 'index': 0}","[{'role': 'user', 'content': '读取文件，统计数字列与非数字列的...",tool_agent
1,code,"[{'role': 'user', 'content': '读取文件，统计数字列与非数字列的...",text,"{'style': 'rule', 'ground_truth': ''}","{'split': 'train', 'index': 1}","[{'role': 'user', 'content': '读取文件，统计数字列与非数字列的...",tool_agent
2,code,"[{'role': 'user', 'content': '读取文件，统计数字列与非数字列的...",text,"{'style': 'rule', 'ground_truth': ''}","{'split': 'train', 'index': 2}","[{'role': 'user', 'content': '读取文件，统计数字列与非数字列的...",tool_agent
3,code,"[{'role': 'user', 'content': '读取文件，统计数字列与非数字列的...",text,"{'style': 'rule', 'ground_truth': ''}","{'split': 'train', 'index': 3}","[{'role': 'user', 'content': '读取文件，统计数字列与非数字列的...",tool_agent
4,code,"[{'role': 'user', 'content': '读取文件，统计数字列与非数字列的...",text,"{'style': 'rule', 'ground_truth': ''}","{'split': 'train', 'index': 4}","[{'role': 'user', 'content': '读取文件，统计数字列与非数字列的...",tool_agent

In [8]:
train_df.to_parquet('./train_code.parquet')